### PR TITLE
big sur compability

### PR DESCRIPTION
**Pull request by renopp**
big sur compability

### CODE REVIEW

**Comment by renopp** [comment]
@GeuntaBuwono @99ridho can you confirm it is work or something error when you upgrade to Big Sur?

**Comment by GeuntaBuwono** [comment]
on it sir @renopp

**Comment by 99ridho** [comment]
On progress pak

update
Screen Shot 2020-11-14 at 00 52 22

so far so gud 🤘 , sorry lil'bit forget to change smbios before this wkwk

**Review by 99ridho — APPROVED** [review]

**Comment by GeuntaBuwono** [comment]
on next PR please make a point what you add and what you remove on plist on PR description. it's really helpful.

**Comment by GeuntaBuwono** [comment]
have you tried this [Dortania Big Sur](https://dortania.github.io/OpenCore-Install-Guide/extras/big-sur/#table-of-contents) ??

**Pull request merged**
